(define (install-scheme-number-package)
	(define (tag x)
		(attach-tag 'scheme-number x))
	(put 'add 'scheme-number (lambda (x y) (tag (+ x y))))
	(put 'sub 'scheme-number (lambda (x y) (tag (- x y))))
	(put 'mul 'scheme-number (lambda (x y) (tag (* x y))))
	(put 'div 'scheme-number (lambda (x y) (tag (/ x y))))
	(put 'make 'scheme-number (lambda (x) (tag x)))
'done)
