(define (install-scheme-number-package)
	(define (tag x)
		(attach-tag 'scheme-number x))
	(put 'add '(scheme-number scheme-number)(lambda (x y) (tag (+ x y))))
	(put 'sub '(scheme-number scheme-number)(lambda (x y) (tag (- x y))))
	(put 'mul '(scheme-number scheme-number)(lambda (x y) (tag (* x y))))
	(put 'div '(scheme-number scheme-number)(lambda (x y) (tag (/ x y))))
	(put 'eq  '(scheme-number scheme-number) (lambda (n1 n2) (equal? n1 n2)))
	(put 'make 'scheme-number (lambda (x) (tag x)))
'done)
