(define (install-rectangular-package)
	;;internal procedures
	(define (real-part z) (car z))
	(define (image-part z) (cdr z))
	(define (make-from-real-image x y) (cons x y))
	(define (magnitude z)
		(sqrt (+ (square (real-part z)) (square (image-part z)))))
	(define (angle z)
		(atan (image-part z) (real-part z)))
	(define (make-from-mag-ang r a)
		(cons (* r (cos a)) (* r (sin a))))

	;;interface to the rest of system
	(define (tag x) (attach-tag 'rectangular x))
	(put 'real-part '(rectangular) real-part)
	(put 'image-part '(rectangular)image-part)
	(put 'magnitude '(rectangular) magnitude)
	(put 'angle '(rectangular) angle)
	(put 'eq '(rectangular rectangular) (lambda (n1 n2) (equal? n1 n2)))
	(put 'eq '(rectangular polar) (lambda (n1 n2) (equal? n1 (make-from-mag-ang (car n2) (cdr n2)))))
	(put 'make-from-real-image 'rectangular (lambda (x y) (tag (make-from-real-image x y))))
	(put 'make-from-mag-ang 'rectangular (lambda (r a) (tag (make-from-mag-ang r a))))
'done)
