(define (install-rectangular-package)
;;internal procedures
(define (real-part z) (car z))
(define (image-part z) (cdr z))
(define (make-from-real-imag x y) (cons x y))
(define (magnitude z)
	(sqrt (+ (square (real-part z)) (square (image-part z)))))
(define (angle z)
	(atan (image-part z) (real-part z)))
(define (make-from-mag-ang r a)
	(cons (* r (cos a)) (* r (sin a))))

;;interface to the rest of system
(define (tag x) (attach-tag 'rectangular x))
(put 'real-part 'rectangular real-part)
(put 'image-part 'rectangular image-part)
(put 'magnitude 'rectangular magnitude)
(put 'angle 'rectangular angle)
(put 'make-from-real-image 'rectangular (lambda (x y) (tag (make-from-real-imag x y))))
(put 'make-from-mag-ang 'rectangular (lambda (r a) (tag (make-from-mag-ang r a))))
'done)
