(define (count-change count)
	(define (first-denomination kind-of-coins)
		(cond ((= kind-of-coins 1) 1)
				((= kind-of-coins 2) 5)
				((= kind-of-coins 3) 10)
				((= kind-of-coins 4)	25)
				((= kind-of-coins 5) 50)))
	(define (cc count kind-of-coins)
		(cond ((= count 0) 1)
				((or (< count 0) (= kind-of-coins 0)) 0)
				(else (+ (cc count (- kind-of-coins 1)) 
							(cc (- count (first-denomination kind-of-coins)) kind-of-coins)))))
	(cc count 5)
)

